### ISSUE TITLE
Unexpected error /ffll command

### ISSUE THREAD

**Issue by BeSlightly** [maributt/FFLogsLookupPlugin#1]
In the plugin's description on the pluginsinstaller it states that using the command
"/fflogs first_name last_name world" or "/ffll placeholder world", you'd be able to look up a player's logs.

This feature seems to be broken for me, everytime I run the command my FFXIV sends an unexpected error, screenshot attached:
![Screenshot_6](https://user-images.githubusercontent.com/80231852/113466655-c4c39500-943d-11eb-814d-cce2c9496780.png)

Note: I'm running many plugins and didn't try only running your plugin yet, I can test that if needed. Also got stuff like gshade installed, if it might be related. The crash only occurs when running the command tough.

I also already tried running sfc /scannow and reinstalling .net Framework.
I'm running Windows 10 Version 20H2

**Comment by maributt** [comment]
So sorry I only saw the issue just now!
The text command was mainly a temporary way for me to mess with the FFLogs API so what happened is I updated some code and didn't retroactively change the command's behavior! I'll fix this very soon as well as polish it properly... and hope it's not been too much trouble!

**Comment by maributt** [comment]
This should now be fixed! Let me know if there's any more crashes happening at all, I also updated the plugin repository to the new fixed version so you should just be able to update it from there!
