### ISSUE TITLE
How can I install the plugin?

### ISSUE THREAD

**Issue by rosario1510** [maributt/FFLogsLookupPlugin#3]
Hello, I can't figure out how to install the plugin
I downloaded the zip but I have no idea what is inside
Thank you!

**Comment by maributt** [comment]
Hello! You don't need to download the zip to install anything at all.
If you're already using [xivlauncher](https://github.com/goatcorp/FFXIVQuickLauncher) you can follow the little writeup I have over [here](https://github.com/maributt/xivplugins) to get things set up! 
Hope it helps, let me know if there's anything else.
